language: python

python:

  - "3.5.4"

before_install:
  - sudo apt-get update
  # - sudo apt-get install libgdal-dev gdal-bin
  # You may want to periodically update this, although the conda update
  # conda line below will keep everything up-to-date.  We do this
  # conditionally because it saves us some downloading if the version is
  # the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda list
  #- sudo rm -rf /dev/shm
  #- sudo ln -s /run/shm /dev/shm
env:
  - GDAL_DATA=/usr/share/gdal/2.2/
install:
  - conda create -n test-environment -c conda-forge python=$TRAVIS_PYTHON_VERSION pip nose cython numpy matplotlib pandas gdal scipy fiona
  - source activate test-environment
  #- if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then conda install --yes imaging; else pip install pillow; fi
  - pip install pillow
  - pip install pytest pytest-cov # not yet available for py3 in anaconda
  - pip install python-coveralls
  - pip install networkx --upgrade
  - pip install -r requirements.txt

script:
  - cd tests/
  - py.test


