name: hrm
channels:
    - conda-forge
dependencies:
  - boto3=1.9.66
  - geopandas=0.4.0
  - osmnx=0.8.2
  - psycopg2=2.7.6.1
  - rasterio=1.0.13
  - requests=2.21.0
  - rtree=0.8.3
  - flask=1.0.2
  - vs2015_runtime=14
  - gdal=2.3.2
  - h5py=2.8.0
  - numpy=1.15.4
  - pandas=0.23.4
  - tensorflow=1.12.0
  - earthengine-api
  - georasters=0.5.11
  - mlxtend=0.13.0
  - pyyaml=3.13
  - rasterstats=0.12.1
  - scikit-image=0.14.1
  - scikit-learn=0.19.1
  - geojson
